### ISSUE TITLE
IllegalArgumentException when downloading EMX with meta

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-EMX-downloader#30]
### How to reproduce
Follow test case 3 in the test plan:
1. Upload *it_emx_datatypes.xlsx* to test server
2. Run downloader with: ```-f test.xlsx -u <url_to_testserver> -a <user> -p <password> -m it_emx_datatypes_TypeTest```

### Expected result
EMX is downloaded without problems

### Actual result
```java
java.lang.IllegalArgumentException
An error occurred:
	at org.molgenis.downloader.api.metadata.Package.from(Package.java:31)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.molgenis.downloader.client.MetadataRepositoryImpl.createPackage(MetadataRepositoryImpl.java:67)
	at org.molgenis.downloader.client.MolgenisV3MetadataConverter.toPackage(MolgenisV3MetadataConverter.java:53)
	at org.molgenis.downloader.client.MolgenisRestApiClient.lambda$streamEntityData$0(MolgenisRestApiClient.java:143)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:891)

	at org.molgenis.downloader.client.MolgenisRestApiClient.streamEntityData(MolgenisRestApiClient.java:142)
	at org.molgenis.downloader.api.MolgenisClient.streamEntityData(MolgenisClient.java:19)
	at org.molgenis.downloader.client.MolgenisRestApiClient.streamMetadata(MolgenisRestApiClient.java:178)
	at org.molgenis.downloader.emx.EMXClient.downloadEMX(EMXClient.java:49)
	at org.molgenis.downloader.Downloader.run(Downloader.java:122)
	at org.molgenis.downloader.Downloader.main(Downloader.java:46)
java.lang.NullPointerException
An error occurred:
	at org.molgenis.downloader.emx.MetadataFilter.getIncludedEntities(MetadataFilter.java:45)
	at org.molgenis.downloader.emx.EMXClient.downloadEMX(EMXClient.java:50)
	at org.molgenis.downloader.Downloader.run(Downloader.java:122)
	at org.molgenis.downloader.Downloader.main(Downloader.java:46)

Process finished with exit code 0
```

**Comment by bartcharbon** [comment]
maybe this is because the "4.0" PR is not accepted?
