### ISSUE TITLE
When downloading a big dataset (~66.000) I get exception

### ISSUE THREAD

**Issue by marikaris** [molgenis/molgenis-EMX-downloader#43]
When downloading big file (m103), I get exception after downloading from: https://molgenis103.gcc.rug.nl/api/v2/VKGL_UMCG?start=11500: 
-a YOURUSERNAME -p YOURPASSWORD -f test5.xlsx -i -u https://molgenis103.gcc.rug.nl/ VKGL_consensus -o -d
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.resize(Saver.java:1700)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.preEmit(Saver.java:1303)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.emit(Saver.java:1190)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.emitElement(Saver.java:962)
	at org.apache.xmlbeans.impl.store.Saver.processElement(Saver.java:476)
	at org.apache.xmlbeans.impl.store.Saver.process(Saver.java:307)
	at org.apache.xmlbeans.impl.store.Saver$TextSaver.saveToString(Saver.java:1864)
	at org.apache.xmlbeans.impl.store.Cursor._xmlText(Cursor.java:546)
	at org.apache.xmlbeans.impl.store.Cursor.xmlText(Cursor.java:2436)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.xmlText(XmlObjectBase.java:1500)
	at org.apache.poi.xssf.model.SharedStringsTable.getKey(SharedStringsTable.java:142)
	at org.apache.poi.xssf.model.SharedStringsTable.addEntry(SharedStringsTable.java:188)
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:462)
	at org.apache.poi.xssf.usermodel.XSSFCell.setCellValue(XSSFCell.java:426)
	at org.molgenis.downloader.emx.excel.ExcelSheet.writeRow(ExcelSheet.java:31)
	at org.molgenis.downloader.emx.EMXEntityConsumer.accept(EMXEntityConsumer.java:43)
	at org.molgenis.downloader.emx.EMXEntityConsumer.accept(EMXEntityConsumer.java:16)
	at org.molgenis.downloader.client.MolgenisRestApiClient.lambda$streamEntityData$0(MolgenisRestApiClient.java:148)
	at org.molgenis.downloader.client.MolgenisRestApiClient$$Lambda$4/1778629809.accept(Unknown Source)
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:891)
	at org.molgenis.downloader.client.MolgenisRestApiClient.streamEntityData(MolgenisRestApiClient.java:147)
	at org.molgenis.downloader.emx.EMXClient.downloadEMX(EMXClient.java:58)
	at org.molgenis.downloader.Downloader.run(Downloader.java:141)
	at org.molgenis.downloader.Downloader.main(Downloader.java:53)
```

**Comment by marikaris** [comment]
when adding -t 500 it does work
