### ISSUE TITLE
Cannot reliably download large datasets from servers < 6.x

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-EMX-downloader#61]
Downloader doesn't specify sort for large data sets, which may trigger  https://github.com/molgenis/molgenis/issues/6836 on servers with version below 6.x

**Comment by djvanenckevort** [comment]
Should be fixed now? Can close ticket?

**Comment by cpavanrun** [comment]
I am running into issues with any entity with a number larger than pageSize. And I am wondering if this is the cause? Should this be fixed for versions below 6.x?

```
[ERROR] - Error streaming entity data for sys_FileMeta.
org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
```

**Comment by marijevdgeest** [comment]
Hi Chris @cpavanrun , 

Can you open a new issue and provide us with more information, so we can reproduce this?
If I look at the error, it seems there can't be a connection established with localhost:8080, are you sure the Molgenis is running there?
